spring:
  application:
    name: health-tracker-api
  profiles:
    default: local
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/repick}
      auto-index-creation: true

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

server:
  port: ${PORT:8080}
